version: "3.5"

services:
  slackbot:
    build:
      context: ./slackbot
    environment:
      - SLACK_BOT_TOKEN=xoxb
      - SLACK_OAUTH_TOKEN=xoxp
    volumes: 
      - ./slackbot:/opt/slackbot
      - ./secrets/secrets:/home/slackbot/secrets
    restart: always
